# Generated by Django 4.1.1 on 2022-10-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300)),
                ('title_en', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('count_of_rating', models.IntegerField()),
                ('warranty', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.urls')),
            ],
        ),
    ]
